# Generated by Django 2.2.18 on 2022-11-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Post',
        ),
    ]
