# Generated by Django 4.1.3 on 2022-12-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_connected',
            field=models.IntegerField(),
        ),
    ]
