# Generated by Django 4.1.3 on 2022-12-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_comment_post_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_connected',
            field=models.IntegerField(),
        ),
    ]
