# Generated by Django 4.1.3 on 2022-12-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_post_idin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='idin',
        ),
    ]
