# Generated by Django 4.1.3 on 2022-12-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='kaveh', max_length=30),
        ),
    ]
